# Generated by Django 5.1.5 on 2025-01-31 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20250131_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.CharField(default='Sem descrição', max_length=255),
        ),
    ]
