# Generated by Django 5.1.5 on 2025-02-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_transaction_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=7),
        ),
    ]
