# Generated by Django 5.1.5 on 2025-02-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_remove_transaction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(default='default_category', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('income', 'Receita'), ('expense', 'Despesa')], max_length=7),
        ),
    ]
