# Generated by Django 5.1.5 on 2025-02-01 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_transaction_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='category',
        ),
    ]
